/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-07-28 18:48:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.pages.projetos.termoabertura;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class termoaberturaconsulta_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/web/pages/projetos/termoabertura/../../header-title.jsp", Long.valueOf(1402583704000L));
    _jspx_dependants.put("/web/pages/projetos/termoabertura/../../botoes-consulta.jsp", Long.valueOf(1404499918000L));
    _jspx_dependants.put("/web/pages/projetos/termoabertura/../../messages.jsp", Long.valueOf(1402591128000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!-- Datatable inside panel body -->\n");
      out.write("\n");
      out.write("<!-- Page header -->\n");
      out.write("<div class=\"page-header\">\n");
      out.write("\t<div class=\"page-title\">\n");
      out.write("\t\t<h3>\n");
      out.write("\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${titulo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" <small>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${subtitulo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</small>\n");
      out.write("\t\t</h3>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!-- /page header -->\n");
      out.write("\n");
      out.write("<!-- Breadcrumbs line -->\n");
      out.write("<div class=\"breadcrumb-line\">\n");
      out.write("\t<ul class=\"breadcrumb\">\n");
      out.write("\t\t<li><a data-link=\"blank.admin\">Home</a></li>\n");
      out.write("\t\t<li><a>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${subMenu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a></li>\n");
      out.write("\t\t<li class=\"active\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuAtivo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</li>\n");
      out.write("\t</ul>\n");
      out.write("</div>\n");
      out.write("<!-- /breadcrumbs line -->");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"panel panel-default panel-body\">\n");
      out.write("\t<div class=\"panel form-group\">\n");
      out.write("\t\t<div class=\"col-md-1 text-right\">\n");
      out.write("\t\t\t<label class=\"control-label text-right\">Pesquisar por: </label>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-sm-2\">\n");
      out.write("\t\t\t<select id=\"ParametroPesquisa\" class=\"form-control\">\n");
      out.write("\t\t\t\t<option value=\"Versao\">Versão</option>\n");
      out.write("\t\t\t\t<option value=\"Versao\">Versão</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"col-sm-3\">\n");
      out.write("\t\t\t<input id=\"PesquisarPor\" type=\"text\" autofocus=\"autofocus\" autocomplete=\"off\" class=\"form-control\" tabindex=\"3\" />\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"col-sm-2 \">\n");
      out.write("\t\t\t<button tabindex=\"4\" title=\"Clique para pesquisar [Atalho: ENTER]\" class=\"BotaoPesquisar btn btn-default\">Pesquisar</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-sm-10\"></div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\n");
      out.write("\t<div class=\"panel-body\">\n");
      out.write("\t\t<div class=\"DataGridConsulta\" data-page=\"termoaberturaconsulta.grid.action\" data-page-size=\"8\" data-detail-page=\"termoaberturacadastro.action\"></div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\n");
      out.write("<!-- <div class=\"form-actions text-left\">\n");
      out.write("\t<button class=\"BotaoNavegacaoPrimeiro btn btn-default btn-icon tip\" title=\"Primeiro [Home]\">\n");
      out.write("\t\t<i class=\"icon-first\"></i>\n");
      out.write("\t</button>\n");
      out.write("\t<button class=\"BotaoNavegacaoAnterior btn btn-default btn-icon tip\" title=\"Anterior [&larr;/PgUp]\">\n");
      out.write("\t\t<i class=\"icon-previous\"></i>\n");
      out.write("\t</button>\n");
      out.write("\t<button class=\"BotaoNavegacaoProximo btn btn-default btn-icon tip\" title=\"Próximo [&rarr;/PgDown]\">\n");
      out.write("\t\t<i class=\"icon-next\"></i>\n");
      out.write("\t</button>\n");
      out.write("\t<button class=\"BotaoNavegacaoUltimo btn btn-default btn-icon tip\" title=\"Último [End]\">\n");
      out.write("\t\t<i class=\"icon-last\"></i>\n");
      out.write("\t</button>\n");
      out.write("</div>\n");
      out.write(" -->\n");
      out.write("<div class=\"FormularioBotoes form-actions\">\n");
      out.write("\t<div class=\"text-left col-md-6\">\n");
      out.write("\t\t<button class=\"BotaoNavegacaoPrimeiro btn btn-default btn-icon tip\" title=\"Primeiro [Home]\">\n");
      out.write("\t\t\t<i class=\"icon-first\"></i>\n");
      out.write("\t\t</button>\n");
      out.write("\t\t<button class=\"BotaoNavegacaoAnterior btn btn-default btn-icon tip\" title=\"Anterior [&larr;/PgUp]\">\n");
      out.write("\t\t\t<i class=\"icon-previous\"></i>\n");
      out.write("\t\t</button>\n");
      out.write("\t\t<button class=\"BotaoNavegacaoProximo btn btn-default btn-icon tip\" title=\"Próximo [&rarr;/PgDown]\">\n");
      out.write("\t\t\t<i class=\"icon-next\"></i>\n");
      out.write("\t\t</button>\n");
      out.write("\t\t<button class=\"BotaoNavegacaoUltimo btn btn-default btn-icon tip\" title=\"Último [End]\">\n");
      out.write("\t\t\t<i class=\"icon-last\"></i>\n");
      out.write("\t\t</button>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<div class=\"text-right col-md-6\">\n");
      out.write("\t\n");
      out.write("\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customButtons}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("\t\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</div>");
      out.write('\n');
      out.write('	');
      out.write("<!-- \n");
      out.write("<div class=\"modal modal-flex fade\" id=\"flexModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"flexModalLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n");
      out.write("                <h4 class=\"modal-title\" id=\"flexModalLabel\">TITULO</h4>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <p>MENSAGEM</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button type=\"button\" class=\"btn btn-default btn-modal-flex-nao\" data-dismiss=\"modal\">Não</button>\n");
      out.write("                <button type=\"button\" class=\"btn btn-green btn-modal-flex-sim\">Sim</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        /.modal-content\n");
      out.write("    </div>\n");
      out.write("    /.modal-dialog\n");
      out.write("</div>\n");
      out.write("-->\n");
      out.write("\n");
      out.write("<div id=\"small_modal\" class=\"modal fade modal-confirmacao-sim-nao\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("\t<div class=\"modal-dialog modal-sm\">\n");
      out.write("\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\"><i class=\"icon-accessibility\"></i> TITULO</h4>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"modal-body with-padding\">\n");
      out.write("\t\t\t\t<p>One fine body&hellip;</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t<button class=\"btn btn-warning btn-modal-flex-nao\" data-dismiss=\"modal\">Não</button>\n");
      out.write("\t\t\t\t<button class=\"btn btn-primary btn-modal-flex-sim\" data-dismiss=\"modal\">Sim</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!-- /datatable inside panel body -->\n");
      out.write("\n");
      out.write("<!-- /datatable inside panel body -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction alterarTermo(operacao, funcaoOk) {\n");
      out.write("\t\tif (!registroSelecionado2()) {\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tvar paginaCadastro = \"termoaberturacadastro.action\";\n");
      out.write("\t\tvar paginaBase = paginaCadastro.split(\".\")[0];\n");
      out.write("\t\tvar paginaFinal = paginaBase + \".\" + operacao + \".\" + paginaCadastro.split(\".\")[1];\n");
      out.write("\t\n");
      out.write("\t\tpaginaFinal += \"?\" + getSelectedDataId();\n");
      out.write("\n");
      out.write("\t\tvar params = {\n");
      out.write("\t\t\t'operacao' : operacao\n");
      out.write("\t\t};\n");
      out.write("\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl : paginaFinal,\n");
      out.write("\t\t\ttype : 'POST',\n");
      out.write("\t\t\tdata : params,\n");
      out.write("\t\t\tbeforeSend : function(data) {\n");
      out.write("\t\t\t\t// console.log(\"loading...\");\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess : function(data) {\n");
      out.write("\n");
      out.write("\t\t\t\tvar retorno = $.parseJSON(data);\n");
      out.write("\n");
      out.write("\t\t\t\tif (retorno.sucesso) {\n");
      out.write("\t\t\t\t\tmensagemInfo(retorno.mensagem);\n");
      out.write("\t\t\t\t\tloadDataGrid();\n");
      out.write("\t\t\t\t\tfuncaoOk();\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tmensagemErro(retorno.mensagem);\n");
      out.write("\t\t\t\t\t$(\"#\" + retorno.fieldFocus).focus();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\terror : function(erro) {\n");
      out.write("\t\t\t\tconsole.log(\"Erro no load ajax! \" + erro);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t$(\".BotaoVoltarProjeto\").click(function() {\n");
      out.write("\t\tvar paginaAcoes = \"projetoconsulta.action\";\n");
      out.write("\t\tloadPage(paginaAcoes);\n");
      out.write("\t\tloadJs(\"web/pages/js/consulta.js\");\n");
      out.write("\t\tloadJs(\"web/pages/js/load.js\");\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\".BotaoFinalizarTermo\").click(function() {\n");
      out.write("\t\tconfirmacaoModal('Confirma a finalização deste termo?', 'Confirmação', function() {\n");
      out.write("\t\t\t// Funcao sim - Finaliza o termo\n");
      out.write("\t\t\talterarTermo('finalizar');\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\".BotaoNovo2\").click(function() {\n");
      out.write("\t\tif (registroSelecionado2()) {\n");
      out.write("\t\t\tconfirmacaoModal('Deseja iniciar um novo termo com base na versão selecionada?', 'Confirmação', function() {\n");
      out.write("\t\t\t\t// Funcao sim - Finaliza o termo\n");
      out.write("\t\t\t\talterarTermo('copiar', function() {\n");
      out.write("\t\t\t\t\t// Se gerou corretamente, editar a versao que esta em ultimo\n");
      out.write("\t\t\t\t\tsetTimeout(function() {\n");
      out.write("\t\t\t\t\t\teditar();\t\n");
      out.write("\t\t\t\t\t}, 1500);\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t// TODO\n");
      out.write("\t\t\t}, function() {\n");
      out.write("\t\t\t\t // Nao - faz o padrao, novo registro somente.\n");
      out.write("\t\t\t\tnovo();\n");
      out.write("\t\t\t});\t\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tnovo();\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\".BotaoCancelarTermo\").click(function() {\n");
      out.write("\t\tconfirmacaoModal('Confirma o cancelamento deste termo?', 'Confirmação', function() {\n");
      out.write("\t\t\t// Funcao sim - Cancela o termo\n");
      out.write("\t\t\talterarTermo('cancelar');\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /web/pages/projetos/termoabertura/termoaberturaconsulta.jsp(29,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("customButtons");
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_c_005fset_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_c_005fset_005f0.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t<button title=\"Voltar para a consulta de projetos\" class=\"BotaoVoltarProjeto btn btn-lg btn-success tip\">\n");
        out.write("\t\t\t<i class=\"icon-undo2\"></i> Voltar para Projetos\n");
        out.write("\t\t</button>\n");
        out.write("\t\t\n");
        out.write("\t\t<button title=\"Gerar PDF\" class=\"BotaoGerarPDF btn btn-lg btn-info tip\">\n");
        out.write("\t\t\t<i class=\"icon-file-pdf\"></i> Gerar PDF\n");
        out.write("\t\t</button>\n");
        out.write("\t\t\n");
        out.write("\t\t<button title=\"Finalizar Termo\" class=\"BotaoFinalizarTermo btn btn-lg btn-primary tip\">\n");
        out.write("\t\t\t<i class=\"icon-checkmark3\"></i> Finalizar Termo\n");
        out.write("\t\t</button>\n");
        out.write("\t\t\n");
        out.write("\t\t<button title=\"Finalizar Termo\" class=\"BotaoCancelarTermo btn btn-lg btn-danger tip\">\n");
        out.write("\t\t\t<i class=\"icon-cancel-circle2\"></i> Cancelar Termo\n");
        out.write("\t\t</button>\n");
        out.write("\t\t\n");
        out.write("\t\t<button type=\"button\" class=\"BotaoNovo2 btn btn-lg btn-primary tip\" title=\"Novo Registro (Ctrl + N)\">\n");
        out.write("\t\t\t<i class=\"icon-plus-circle\"></i> Novo\n");
        out.write("\t\t</button>\n");
        out.write("\t\t\n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_c_005fset_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /web/pages/projetos/termoabertura/termoaberturaconsulta.jsp(56,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("hideExcluir");
    // /web/pages/projetos/termoabertura/termoaberturaconsulta.jsp(56,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/web/pages/projetos/termoabertura/termoaberturaconsulta.jsp(56,1) 'hide'",_el_expressionfactory.createValueExpression("hide",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent(null);
    // /web/pages/projetos/termoabertura/termoaberturaconsulta.jsp(57,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("hideNovo");
    // /web/pages/projetos/termoabertura/termoaberturaconsulta.jsp(57,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/web/pages/projetos/termoabertura/termoaberturaconsulta.jsp(57,1) 'hide'",_el_expressionfactory.createValueExpression("hide",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /web/pages/projetos/termoabertura/../../botoes-consulta.jsp(38,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty hideNovo}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t<button type=\"button\" class=\"BotaoNovo btn btn-lg btn-primary tip\" title=\"Novo Registro (Ctrl + N)\">\n");
        out.write("\t\t\t\t<i class=\"icon-plus-circle\"></i> Novo\n");
        out.write("\t\t\t</button>\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /web/pages/projetos/termoabertura/../../botoes-consulta.jsp(44,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty hideEditar}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t<button type=\"button\" class=\"BotaoEditar btn btn-lg btn-success tip\" title=\"Editar Registro Selecionado (Ctrl + E)\">\n");
        out.write("\t\t\t\t<i class=\"icon-pencil4\"></i> Editar\n");
        out.write("\t\t\t</button>\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /web/pages/projetos/termoabertura/../../botoes-consulta.jsp(50,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty hideExcluir}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t<button type=\"button\" class=\"BotaoExcluir btn btn-lg btn-danger tip\" title=\"Excluir Registro Selecionado (Ctrl + Del)\">\n");
        out.write("\t\t\t\t<i class=\"icon-minus-circle\"></i> Excluir\n");
        out.write("\t\t\t</button>\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }
}
