/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-07-04 19:00:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.pages.acesso.usuario;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class usuariocadastro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/web/pages/acesso/usuario/../../botoes-cadastro.jsp", Long.valueOf(1402086481000L));
    _jspx_dependants.put("/web/pages/acesso/usuario/../../header-title.jsp", Long.valueOf(1402583704000L));
    _jspx_dependants.put("/web/pages/acesso/usuario/../../utils/lista_imagens.jsp", Long.valueOf(1402335324000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("<!-- Page header -->\n");
      out.write("<div class=\"page-header\">\n");
      out.write("\t<div class=\"page-title\">\n");
      out.write("\t\t<h3>\n");
      out.write("\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${titulo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" <small>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${subtitulo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</small>\n");
      out.write("\t\t</h3>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!-- /page header -->\n");
      out.write("\n");
      out.write("<!-- Breadcrumbs line -->\n");
      out.write("<div class=\"breadcrumb-line\">\n");
      out.write("\t<ul class=\"breadcrumb\">\n");
      out.write("\t\t<li><a data-link=\"blank.admin\">Home</a></li>\n");
      out.write("\t\t<li><a>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${subMenu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a></li>\n");
      out.write("\t\t<li class=\"active\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuAtivo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</li>\n");
      out.write("\t</ul>\n");
      out.write("</div>\n");
      out.write("<!-- /breadcrumbs line -->");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"panel panel-body\">\n");
      out.write("\t<form class=\"form-horizontal\" action=\"#\" role=\"form\">\n");
      out.write("\t\t<div class=\"FormularioCadastro FormularioGeral panel panel-default form-group\" data-page-consulta=\"usuarioconsulta.action\" data-page-operacao=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${operacao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" data-page-cadastro=\"usuariocadastro.action\">\n");
      out.write("\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-2 control-label text-right\">C&oacute;digo</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t<input id=\"idUsuario\" type=\"text\" disabled=\"disabled\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.idUsuario }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-2 control-label text-right\">Nome</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t<input id=\"nome\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.nome}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" autofocus=\"autofocus\" class=\"form-control\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-2 control-label text-right\">Login</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t<input id=\"login\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.login}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" autofocus=\"autofocus\" class=\"form-control\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-2 control-label text-right\">Email</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t<input id=\"email\" type=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" autofocus=\"autofocus\" class=\"form-control\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-2 control-label text-right\">Senha</label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t<input id=\"senha\" type=\"password\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.senha}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" autofocus=\"autofocus\" class=\"form-control\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-2 control-label text-right\">Ativo</label>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t<select id=\"ativo\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t<option ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(" value=\"N\">Não</option>\n");
      out.write("\t\t\t\t\t\t\t<option ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(" value=\"S\">Sim</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<label class=\"col-sm-2 control-label text-right\">Perfil</label>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-7\">\n");
      out.write("\t\t\t\t\t\t<select id=\"idPerfil\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t<option >[Selecione o Perfil]</option>\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<label class=\"col-sm-2 control-label text-right\">Foto do usuário</label> <a href=\"#\" class=\"BotaoSelecionarImagem btn btn-primary\" data-image-retorno=\"#imgFoto\" data-input-retorno=\"#pathFoto\"><i class=\"icon-image\"></i> Selecionar imagem</a> <img id=\"imgFoto\" name=\"imgFoto\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.pathFoto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"thumb img-thumbnail\" style=\"max-height: 120px; max-width: 120px; width: auto; height: auto;\" /> <input type=\"hidden\" id=\"pathFoto\" name=\"pathFoto\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.pathFoto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"form-control\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Formulario de imagens -->\n");
      out.write("<div id=\"selecao_imagem\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("\t<div class=\"modal-dialog modal-lg\">\n");
      out.write("\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">\n");
      out.write("\t\t\t\t\t<i class=\"icon-images\"></i> Banco de imagens\n");
      out.write("\t\t\t\t</h4>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"modal-body with-padding\">\n");
      out.write("\t\t\t\t<div class=\"tabbable\">\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-tabs\">\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a id=\"listaImagensLink\" href=\"#tabListaImagens\" data-toggle=\"tab\"><i class=\"icon-windows8\"></i>Lista de imagens</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a id=\"listaImagensUpload\" href=\"#tabEnviarImagens\" data-toggle=\"tab\"><i class=\"icon-cloud-upload\"></i>Enviar imagens</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"tab-content\">\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-pane fade in active\" id=\"tabListaImagens\">\n");
      out.write("\t\t\t\t\t\t\t<!-- Load dinamico -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-pane body fade\" id=\"tabEnviarImagens\"></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-warning\" data-dismiss=\"modal\">Fechar</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- /modal with tabs -->\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t// Load da pagina no click\n");
      out.write("\t$(\"#listaImagensLink\").click(function(e) {\n");
      out.write("\t\tloadImagens();\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t$(\"#listaImagensUpload\").click(function(e) {\n");
      out.write("\t\t$(\"#tabEnviarImagens\").load(\"listaimagem.upload.action\");\n");
      out.write("\t\t\n");
      out.write("\t\tsetTimeout(function() {\n");
      out.write("\t\t\t$(\".multiple-uploader-images\").pluploadQueue({\n");
      out.write("\t\t\t\truntimes : 'html5, html4',\n");
      out.write("\t\t\t\turl : 'upload/images',\n");
      out.write("\t\t\t\tchunk_size : '1mb',\n");
      out.write("\t\t\t\tunique_names : false,\n");
      out.write("\t\t\t\tfilters : {\n");
      out.write("\t\t\t\t\tmax_file_size : '10mb',\n");
      out.write("\t\t\t\t\tmime_types : [ {\n");
      out.write("\t\t\t\t\t\ttitle : \"Image files\",\n");
      out.write("\t\t\t\t\t\textensions : \"jpg,gif,png,bmp\"\n");
      out.write("\t\t\t\t\t}, {\n");
      out.write("\t\t\t\t\t\ttitle : \"Zip files\",\n");
      out.write("\t\t\t\t\t\textensions : \"zip\"\n");
      out.write("\t\t\t\t\t} ]\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tresize : {\n");
      out.write("\t\t\t\t\twidth : 320,\n");
      out.write("\t\t\t\t\theight : 240,\n");
      out.write("\t\t\t\t\tquality : 90\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}, tempo);\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\tfunction loadImagens() {\n");
      out.write("\t\t$(\"#tabListaImagens\").load(\"listaimagem.datatable.action\", function(response, status, xhr) {\n");
      out.write("\t\t\toTable = $('.datatable-images table').dataTable({\n");
      out.write("\t\t\t\t\"bJQueryUI\" : false,\n");
      out.write("\t\t\t\t\"bAutoWidth\" : false,\n");
      out.write("\t\t\t\t\"iDisplayLength\" : 5,\n");
      out.write("\t\t\t\t\"sPaginationType\" : \"full_numbers\",\n");
      out.write("\t\t\t\t\"sDom\" : '<\"datatable-header\"fl><\"datatable-scroll\"t><\"datatable-footer\"ip>',\n");
      out.write("\t\t\t\t\"oLanguage\" : {\n");
      out.write("\t\t\t\t\t\"sSearch\" : \"<span>Filtrar:</span> _INPUT_\",\n");
      out.write("\t\t\t\t\t\"sLengthMenu\" : \"\",\n");
      out.write("\t\t\t\t\t\"oPaginate\" : {\n");
      out.write("\t\t\t\t\t\t\"sFirst\" : \"Primeiro\",\n");
      out.write("\t\t\t\t\t\t\"sLast\" : \"Último\",\n");
      out.write("\t\t\t\t\t\t\"sNext\" : \">\",\n");
      out.write("\t\t\t\t\t\t\"sPrevious\" : \"<\"\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\t\"fnDrawCallback\" : function() {\n");
      out.write("\t\t\t\t\tloadClickFunction();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\tsetTimeout(function() {\n");
      out.write("\t\t\t/* oTable = $('.datatable-images table').dataTable({\n");
      out.write("\t\t\t\t\"bJQueryUI\" : false,\n");
      out.write("\t\t\t\t\"bAutoWidth\" : false,\n");
      out.write("\t\t\t\t\"iDisplayLength\" : 5,\n");
      out.write("\t\t\t\t\"sPaginationType\" : \"full_numbers\",\n");
      out.write("\t\t\t\t\"sDom\" : '<\"datatable-header\"fl><\"datatable-scroll\"t><\"datatable-footer\"ip>',\n");
      out.write("\t\t\t\t\"oLanguage\" : {\n");
      out.write("\t\t\t\t\t\"sSearch\" : \"<span>Filtrar:</span> _INPUT_\",\n");
      out.write("\t\t\t\t\t\"sLengthMenu\" : \"\",\n");
      out.write("\t\t\t\t\t\"oPaginate\" : {\n");
      out.write("\t\t\t\t\t\t\"sFirst\" : \"Primeiro\",\n");
      out.write("\t\t\t\t\t\t\"sLast\" : \"Último\",\n");
      out.write("\t\t\t\t\t\t\"sNext\" : \">\",\n");
      out.write("\t\t\t\t\t\t\"sPrevious\" : \"<\"\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\t\"fnDrawCallback\" : function() {\n");
      out.write("\t\t\t\t\tloadClickFunction();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}); */\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t// Seta funcao do clique do botao de retornar a imagem\n");
      out.write("\t\t\t///loadClickFunction();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t/* // Ao paginar, chamar evento para dar funcao de click dos botoes, pois sao re-renderizados na paginacao.\n");
      out.write("\t\t\t$(\".datatable-images table\").bind(\"page\", function() {\n");
      out.write("\t\t\t\tsetTimeout(function() {\n");
      out.write("\t\t\t\t\tloadClickFunction();\n");
      out.write("\t\t\t\t}, tempo * 3);\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t// Ao filtrar, chamar evento para dar funcao de click dos botoes, pois sao re-renderizados na paginacao.\n");
      out.write("\t\t\t$(\".datatable-images table\").bind(\"filter\", function() {\n");
      out.write("\t\t\t\tsetTimeout(function() {\n");
      out.write("\t\t\t\t\tloadClickFunction();\n");
      out.write("\t\t\t\t}, tempo * 3);\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t// Ao ordenar, chamar evento para dar funcao de click dos botoes, pois sao re-renderizados na paginacao.\n");
      out.write("\t\t\t$(\".datatable-images table\").bind(\"sort\", function() {\n");
      out.write("\t\t\t\tsetTimeout(function() {\n");
      out.write("\t\t\t\t\tloadClickFunction();\n");
      out.write("\t\t\t\t}, tempo * 3);\n");
      out.write("\t\t\t}); */\n");
      out.write("\n");
      out.write("\t\t\t$(\".dataTables_wrapper tfoot input\").keyup(function() {\n");
      out.write("\t\t\t\toTable.fnFilter(this.value, $(\".dataTables_wrapper tfoot input\").index(this));\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t$('.dataTables_filter input[type=text]').attr('placeholder','Digite o valor da pesquisa...');\n");
      out.write("\t\t\t\n");
      out.write("\t\t}, tempo);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction loadClickFunction() {\n");
      out.write("\t\tconsole.log(\"load click function\");\n");
      out.write("\t\t\n");
      out.write("\t\t$(\".BotaoRetornarImagem\").click(function(e) {\n");
      out.write("\t\t\tconsole.log(\"Clique botao retornar imagem\");\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar file         = $(e.currentTarget).attr(\"data-image-value\")\n");
      out.write("\t\t\tvar imgRetorno   = $(\"#selecao_imagem\").attr(\"data-image-retorno\");\n");
      out.write("\t\t\tvar inputRetorno = $(\"#selecao_imagem\").attr(\"data-input-retorno\");\n");
      out.write("\n");
      out.write("\t\t\tconsole.log(\"Arquivo selecionado: \" + file);\n");
      out.write("\t\t\tconsole.log(imgRetorno);\n");
      out.write("\t\t\tconsole.log(inputRetorno);\n");
      out.write("\n");
      out.write("\t\t\t$(imgRetorno).attr(\"src\", file);\n");
      out.write("\t\t\t$(inputRetorno).attr(\"value\", file);\n");
      out.write("\n");
      out.write("\t\t\t// Forca esconder o modal\n");
      out.write("\t\t\t$('#selecao_imagem').modal('hide');\n");
      out.write("\n");
      out.write("\t\t\t// Remove-te a ti mesmo...\n");
      out.write("\t\t\t$(\"#caixa_selecao_imagem\").remove();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tconsole.log(\"Imagem selecionada\");\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\t\t\t\t");
      out.write("\n");
      out.write("<div class=\"FormularioBotoes form-actions text-right\">\n");
      out.write("\t<button type=\"button\" title=\"Salvar (Ctrl + S)\" class=\"BotaoSalvar btn btn-lg btn-primary tip\">\n");
      out.write("\t\t<i class=\"icon-disk\"></i> Salvar\n");
      out.write("\t</button>\n");
      out.write("\n");
      out.write("\t<button type=\"button\" title=\"Excluir (Ctrl + Del)\" class=\"BotaoExcluir btn btn-lg btn-danger tip\">\n");
      out.write("\t\t<i class=\"icon-minus-circle\"></i> Excluir\n");
      out.write("\t</button>\n");
      out.write("\t<button type=\"button\" title=\"Voltar (Esc)\" class=\"BotaoVoltar btn btn-lg btn-success tip\">\n");
      out.write("\t\t<i class=\"icon-undo2\"></i> Voltar\n");
      out.write("\t</button>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /web/pages/acesso/usuario/usuariocadastro.jsp(50,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ativo == 'N'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("selected=\"selected\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /web/pages/acesso/usuario/usuariocadastro.jsp(51,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ativo == 'S'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("selected=\"selected\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /web/pages/acesso/usuario/usuariocadastro.jsp(62,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/web/pages/acesso/usuario/usuariocadastro.jsp(62,7) '${perfis}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${perfis}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /web/pages/acesso/usuario/usuariocadastro.jsp(62,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("perfil");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t<option ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write(" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${perfil.idPerfil }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${perfil.nome}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /web/pages/acesso/usuario/usuariocadastro.jsp(63,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.idPerfil == perfil.idPerfil}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("selected=\"selected\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }
}
